---
title: "Project description"
---

## Timeline

[Topic ideas](#topic-ideas) due Fri, Feb 18

[Proposal](#project-proposal) due Fri, Mar 18

Slides presentation and [final GitHub repo](#reproducibility---organization) due Thu, Apr 28

[Presentation comments](#presentation-comments) due Sat, Apr 30


### Expectted results

The three primary deliverables for the final project are

-   A ReadMe about the project
-   A written, reproducible report detailing your analysis
-   A GitHub repository corresponding to your report
-   Slides presentation


## ReadMe

For each repo, include the following:

#### Introduction and data

-   Describe the observations and the general characteristics being measured in the data

#### Research question

-   Describe a research question you're interested in answering using this data.

#### Glimpse of data

-   Use the `glimpse` function to provide an overview of each data set


## Project proposal {#project-proposal}

The purpose of the project proposal is to help you think about your analysis strategy early.

Include the following in the proposal:

### Section 1 - Introduction

The introduction section includes

-   an introduction to the subject matter you're investigating
-   the motivation for your research question (citing any relevant literature)
-   the general research question you wish to explore
-   your hypotheses regarding the research question of interest.

### Section 2 - Data description

In this section, you will describe the data set you wish to explore. This includes

-   description of the observations in the data set,
-   description of how the data was originally collected (not how you found the data but how the original curator of the data collected it).

### Section 3 - Analysis approach

In this section, you will provide a brief overview of your analysis approach. This includes:

-   Description of the response variable.
-   Visualization and summary statistics for the response variable.
-   List of variables that will be considered as predictors
-   Regression model technique (multiple linear regression and logistic regression)

### Data dictionary (aka code book)

Submit a data dictionary for all the variables in your data set in the `README` of your project repo, in the `data` folder. Link to this file from your proposal writeup.

### Submission

Push all of your final changes to the GitHub repo, and submit the PDF of your proposal to **Moodle**.

## Draft report {#draft-report}

The purpose of the draft and peer review is to give you an opportunity to get early feedback on your analysis. Therefore, the draft and peer review will focus primarily on the exploratory data analysis, modeling, and initial interpretations.

Write the draft in the **written-report.qmd** file in your project repo. You do not need to submit the draft

Below is a brief description of the sections to focus on in the draft:

### Introduction and data

This section includes an introduction to the project motivation, data, and research question. Describe the data and definitions of key variables. It should also include some exploratory data analysis. All of the EDA won't fit in the paper, so focus on the EDA for the response variable and a few other interesting variables and relationships.

### Methodology

This section includes a brief description of your modeling process. Explain the reasoning for the type of model you're fitting, predictor variables considered for the model including any interactions. Additionally, show how you arrived at the final model by describing the model selection process, any variable transformations (if needed), and any other relevant considerations that were part of the model fitting process.

### Results

In this section, you will output the final model and include a brief discussion of the model assumptions, diagnostics, and any relevant model fit statistics.

This section also includes initial interpretations and conclusions drawn from the model.

<!-- ## Peer review {#peer-review} -->

<!-- Critically reviewing others' work is a crucial part of the scientific process, and STA 210 is no exception. Each lab team will be assigned two other teams's projects to review. Each team should push their draft to their GitHub repo by the due date. One lab in the following week will be dedicated to the peer review, and all reviews will be due by the end of that lab session. -->

<!-- During the peer review process, you will be provided read-only access to your partner teams' GitHub repos. Provide your review in the form of GitHub issues to your partner team's GitHub repo using the issue template provided. The peer review will be graded on the extent to which it comprehensively and constructively addresses the components of the partner team's report: the research context and motivation, exploratory data analysis, modeling, interpretations, and conclusions. -->

<!-- ### Process and questions -->

<!-- Spend \~30 mins to review each team's project. -->

<!-- -   Find your team name on the **Reviewer 1** and **Reviewer 2** columns. -->

<!-- -   For each of the columns, find the name of the team to review in the **Team being reviewed** column. You should already have access to this team's repo. -->

<!-- -   Open the repo of the team you're reviewing, read their project draft, and browser around the rest of their repo. -->

<!-- -   Then, go to the Issues tab in that repo, click on New issue, and click on Get started for the Peer review issue. Fill out this issue, answering the following questions: -->

<!--     -   Peer review by: \[NAME OF TEAM DOING THE REVIEW\] -->

<!--     -   Names of team members that participated in this review: \[FULL NAMES OF TEAM MEMBERS DOING THE REVIEW\] -->

<!--     -   Describe the goal of the project. -->

<!--     -   Describe the data used or collected, if any. If the proposal does not include the use of a specific dataset, comment on whether the project would be strengthened by the inclusion of a dataset. -->

<!--     -   Describe the approaches, tools, and methods that will be used. -->

<!--     -   Is there anything that is unclear from the proposal? -->

<!--     -   Provide constructive feedback on how the team might be able to improve their project. Make sure your feedback includes at least one comment on the statistical modeling aspect of the project, but do feel free to comment on aspects beyond the modeling. -->

<!--     -   What aspect of this project are you most interested in and would like to see highlighted in the presentation. -->

<!--     -   Provide constructive feedback on any issues with file and/or code organization. -->

<!--     -   (Optional) Any further comments or feedback? -->

## Written report {#written-report}

### Introduction and data

This section includes an introduction to the project motivation, data, and research question. Describe the data and definitions of key variables.

#### Grading criteria

The research question and motivation are clearly stated in the introduction, including citations for the data source and any external research. The data are clearly described, including a description about how the data were originally collected and a concise definition of the variables relevant to understanding the report. The data cleaning process is clearly described, including any decisions made in the process (e.g., creating new variables, removing observations, etc.) The explanatory data analysis helps the reader better understand the observations in the data along with interesting and relevant relationships between the variables. It incorporates appropriate visualizations and summary statistics.

### Methodology

This section includes a brief description of your modeling process.

#### Grading criteria

The analysis steps are appropriate for the data and research question.

### Results

Describe the key results from the graph. Focus on the variables that help you answer the research question and that provide relevant context for the reader.

#### Grading criteria

The visualization is clearly assessed, and interesting findings are clearly described. Interpretations of statistical test are used to support the key findings and conclusions, rather than merely visual comparison.

### Discussion + Conclusion

In this section you'll include a summary of what you have learned about your research question along with statistical arguments supporting your conclusions. In addition, discuss the limitations of your analysis and provide suggestions on ways the analysis could be improved. Any potential issues pertaining to the reliability and validity of your data and appropriateness of the statistical analysis should also be discussed here. Lastly, this section will include ideas for future work.

#### Grading criteria

Overall conclusions from analysis are clearly described, and the statistical results are put into the larger context of the subject matter and original research question. There is thoughtful consideration of potential limitations of the data and/or analysis, and ideas for future work are clearly described.

### Organization + formatting

This is an assessment of the overall presentation and formatting of the written report.

#### Grading criteria

The presentation neatly prepared and organized with clear section headers and appropriately sized figures with informative labels. Numerical results are displayed with a reasonable number of digits, and all visualizations are neatly formatted. All citations and links are properly formatted. All code, warnings, and messages are suppressed. Presentation is in time.

### Slides

You need to create presentation slides and record a video presentation that summarize and showcase your project. Introduce your research question and data set, showcase visualizations, and discuss the primary conclusions. These slides should serve as a brief visual addition to your written report and will be graded for content and quality.

The slide deck should have no more than 6 content slides + 1 title slide. Here is a *suggested* outline as you think through the slides; you [**do not**]{.underline} have to use this exact format for the 6 slides.

-   Title Slide
-   Slide 1: Introduce the topic and motivation
-   Slide 2: Previous research that relevant to your hypothess
-   Slide 3: Hypotheses Research questions
-   Slide 4: Introduce the data
-   Slide 5: Calculation
-   Slide 6: Conclusions + future work

## Presentation comments {#presentation-comments}

Each student will be assigned 2 presentations to watch. Your viewing assignments will be posted later in the semester.

Watch the group's video, then click "Reply" to post a question for the group. You may not post a question that's already been asked on the discussion thread. Additionally, the question should be (i) substantive (i.e. it shouldn't be "Why did you use a bar plot instead of a pie chart"?), (ii) demonstrate your understanding of the content from the course, and (iii) relevant to that group's specific presentation, i.e demonstrating that you've watched the presentation.

## Reproducibility + organization

All written work (with exception of presentation slides) should be reproducible, and the GitHub repo should be neatly organized.

The GitHub repo should have the following structure:

-   `README`: Short project description and data dictionary

-   `written-report.qmd` & `written-report.pdf`: Final written report

-   `/data`: Folder that contains the data set for the final project.

-   `/previous-work`: Folder that contains the `topic-ideas` and `project-proposal` files.

-   `/presentation`: Folder with the presentation slides.

    -   If your presentation slides are online, you can put a link to the slides in a `README.md` file in the `presentation` folder.

Points for reproducibility + organization will be based on the reproducibility of the written report and the organization of the project GitHub repo. The repo should be neatly organized as described above, there should be no extraneous files, all text in the README should be easily readable.

## Peer teamwork evaluation

You will be asked to fill out a survey where you rate the contribution and teamwork of each team member by assigning a contribution percentage for each team member. Filling out the survey is a prerequisite for getting credit on the team member evaluation. If you are suggesting that an individual did less than half the expected contribution given your team size (e.g., for a team of four students, if a student contributed less than 12.5% of the total effort), please provide some explanation. If any individual gets an average peer score indicating that this was the case, their grade will be assessed accordingly.

If you have concerns with the teamwork and/or contribution from any team members, please email me by the project video deadline. **You only need to email me if you have concerns**. Otherwise, I will assume everyone on the team equally contributed and will receive full credit for the teamwork portion of the grade.

<!-- ### Grading summary -->

<!-- Grading of the project will take into account the following: -->

<!-- -   Content - What is the quality of research and/or policy question and relevancy of data to those questions? -->

<!-- -   Correctness - Are statistical procedures carried out and explained correctly? -->

<!-- -   Writing and Presentation - What is the quality of the statistical presentation, writing, and explanations? -->

<!-- -   Creativity and Critical Thought - Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project? -->

<!-- -    -->
